#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials cases

# pre-processing
runApplication blockMesh
#runApplication refineMesh
#runApplication checkMesh
runApplication setFields

runApplication decomposePar
foamPostProcess -func "traceSurface" -latestTime
foamPostProcess -func "fillFraction" -latestTime
runApplication reconstructPar

#------------------------------------------------------------------------------