#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../MarangoniWithPhaseChange/0.01 0.01

# pre-processing 
runApplication blockMesh
runApplication checkMesh
runApplication setFields

# run in parallel
#runApplication decomposePar -cellProc
#runParallel $(getApplication)
#runApplication reconstructPar
runApplication $(getApplication)

#------------------------------------------------------------------------------