/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Copyright (C) 2011-2018 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

// * * * * * * * * * * * * * * * * Constructors  * * * * * * * * * * * * * * //

inline Foam::laserParticle::trackingData::trackingData
(
    const Cloud<laserParticle>& spc,
    const interpolationCellPoint<scalar>& alpha1Interp,
    const interpolationCellPoint<vector>& nHatInterp,
    volScalarField& lPower,
    DynamicField<point>& allPositions,
    DynamicField<label>& allTracks,
    DynamicField<scalar>& allPowers
)
:
    particle::trackingData(spc),
    alpha1Interp_(alpha1Interp),
    nHatInterp_(nHatInterp),
    lPower_(lPower),
    allPositions_(allPositions),
    allTracks_(allTracks),
    allPowers_(allPowers)
{}

inline Foam::laserParticle::laserParticle
(
    const polyMesh& mesh,
    const vector& position,
    const scalar d,
    const vector& U,
    const label cellI,
    const label trackIndex,
    const scalar a,
    const label maxReflections
)
:
    particle(mesh, position, cellI),
    d_(d),
    d0_(d),
    U_(U),
    trackIndex_(trackIndex),
    a_(a),
    maxReflections_(maxReflections),
    reflections_(0)
{}


// * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * //

inline const Foam::interpolationCellPoint<Foam::scalar>&
Foam::laserParticle::trackingData::alpha1Interp() const
{
    return alpha1Interp_;
}

inline const Foam::interpolationCellPoint<Foam::vector>&
Foam::laserParticle::trackingData::nHatInterp() const
{
    return nHatInterp_;
}

inline void Foam::laserParticle::trackingData::addToPower(scalar p, label cellI)
{
    lPower_[cellI] += p;
}

inline void Foam::laserParticle::trackingData::append(vector position, label trackIndex, scalar d)
{
    allPositions_.append(position);
    allTracks_.append(trackIndex);
    allPowers_.append(d);
}


// ************************************************************************* //
